name: AutoSell
main: LamPocketVN\AutoSell\main
version: 0.0.3.lpk
api: [3.0.0, 4.0.0]
author: LamPocketVN
description: Auto-Sell plugin
depend: 
- Sell
commands:
  autosell:
    description: "Enable or disable autosell mode !"
    permission: lpkas.command
permissions:
  lpkas.command:
    default: true
